theme: jekyll-theme-minimal
title: [A Data Science Project]
description: [From data collection to web deployment test]

#logo: [[Data Collection](https://justyntyrrell.github.io/Car_Auction_Price_Prediction/#data-collection)]
