theme: jekyll-theme-minimal
title: [A Data Science Project]
description: ['Practicing: data collection, cleaning, preprocessing, exploration, model building, explainability, and web deployment']

#logo: webdemo/pic.jpg
